/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhohang;

import javax.swing.JLayeredPane;

/**
 *
 * @author conganhpham
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        chooseLayer(nhapKhoLayerPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vatTuButton = new javax.swing.JButton();
        nhapKhoButton = new javax.swing.JButton();
        xuatKhoButton = new javax.swing.JButton();
        thongKeButton = new javax.swing.JButton();
        donViButton = new javax.swing.JButton();
        nhaCungCapButton = new javax.swing.JButton();
        khachHangButton = new javax.swing.JButton();
        nhapKhoLayerPane = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        xuatKhoLayerPane = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        vatTuLayerPane = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        donViLayerPane = new javax.swing.JLayeredPane();
        jLabel21 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        nhaCungCapLayerPane = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        khachHangLayerPane = new javax.swing.JLayeredPane();
        jLabel26 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton28 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        thongKeLayerPane = new javax.swing.JLayeredPane();
        jLabel31 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 75));
        setMinimumSize(new java.awt.Dimension(752, 600));
        setPreferredSize(new java.awt.Dimension(752, 600));
        setResizable(false);

        vatTuButton.setText("Vật tư");
        vatTuButton.setPreferredSize(new java.awt.Dimension(100, 100));
        vatTuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vatTuButtonMouseClicked(evt);
            }
        });

        nhapKhoButton.setText("Nhập kho");
        nhapKhoButton.setPreferredSize(new java.awt.Dimension(100, 100));
        nhapKhoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhapKhoButtonMouseClicked(evt);
            }
        });

        xuatKhoButton.setText("Xuất kho");
        xuatKhoButton.setPreferredSize(new java.awt.Dimension(100, 100));
        xuatKhoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xuatKhoButtonMouseClicked(evt);
            }
        });

        thongKeButton.setText("Thống kê");
        thongKeButton.setPreferredSize(new java.awt.Dimension(100, 100));
        thongKeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeButtonMouseClicked(evt);
            }
        });

        donViButton.setText("Đơn vị");
        donViButton.setPreferredSize(new java.awt.Dimension(100, 100));
        donViButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donViButtonMouseClicked(evt);
            }
        });

        nhaCungCapButton.setText("Nhà cung cấp");
        nhaCungCapButton.setPreferredSize(new java.awt.Dimension(100, 100));
        nhaCungCapButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhaCungCapButtonMouseClicked(evt);
            }
        });

        khachHangButton.setText("Khách hàng");
        khachHangButton.setPreferredSize(new java.awt.Dimension(100, 100));
        khachHangButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHangButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Name");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Date");

        jTextField2.setText("jTextField1");

        jLabel3.setText("Quantity");

        jTextField3.setText("jTextField1");

        jLabel4.setText("Customer");

        jButton8.setText("jButton8");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Statuts");

        jTextField4.setText("jTextField1");

        jButton9.setText("add");

        jButton10.setText("eddit");

        jButton11.setText("remove");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        nhapKhoLayerPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhapKhoLayerPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout nhapKhoLayerPaneLayout = new javax.swing.GroupLayout(nhapKhoLayerPane);
        nhapKhoLayerPane.setLayout(nhapKhoLayerPaneLayout);
        nhapKhoLayerPaneLayout.setHorizontalGroup(
            nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhapKhoLayerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhapKhoLayerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nhapKhoLayerPaneLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(nhapKhoLayerPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(131, 131, 131)
                        .addComponent(jButton10)
                        .addGap(53, 53, 53)))
                .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhapKhoLayerPaneLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton11)))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(nhapKhoLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        nhapKhoLayerPaneLayout.setVerticalGroup(
            nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhapKhoLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nhapKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jLabel6.setText("Name");

        jTextField5.setText("jTextField1");

        jLabel7.setText("Date");

        jTextField6.setText("jTextField1");

        jLabel8.setText("Quantity");

        jTextField7.setText("jTextField1");

        jLabel9.setText("Customer");

        jButton12.setText("jButton8");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("Statuts");

        jTextField8.setText("jTextField1");

        jButton13.setText("add");

        jButton14.setText("eddit");

        jButton15.setText("remove");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        xuatKhoLayerPane.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jTextField6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jTextField8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jButton15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        xuatKhoLayerPane.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout xuatKhoLayerPaneLayout = new javax.swing.GroupLayout(xuatKhoLayerPane);
        xuatKhoLayerPane.setLayout(xuatKhoLayerPaneLayout);
        xuatKhoLayerPaneLayout.setHorizontalGroup(
            xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xuatKhoLayerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xuatKhoLayerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(xuatKhoLayerPaneLayout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(xuatKhoLayerPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jButton13)
                        .addGap(131, 131, 131)
                        .addComponent(jButton14)
                        .addGap(53, 53, 53)))
                .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(xuatKhoLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        xuatKhoLayerPaneLayout.setVerticalGroup(
            xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xuatKhoLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(xuatKhoLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jLabel11.setText("Name");

        jTextField9.setText("jTextField1");

        jLabel12.setText("Date");

        jTextField10.setText("jTextField1");

        jLabel13.setText("Quantity");

        jTextField11.setText("jTextField1");

        jLabel14.setText("Customer");

        jButton16.setText("jButton8");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Statuts");

        jTextField12.setText("jTextField1");

        jButton17.setText("add");

        jButton18.setText("eddit");

        jButton19.setText("remove");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        vatTuLayerPane.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jTextField9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jTextField10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jTextField11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jButton16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jComboBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jTextField12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jButton17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jButton18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jButton19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        vatTuLayerPane.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout vatTuLayerPaneLayout = new javax.swing.GroupLayout(vatTuLayerPane);
        vatTuLayerPane.setLayout(vatTuLayerPaneLayout);
        vatTuLayerPaneLayout.setHorizontalGroup(
            vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vatTuLayerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vatTuLayerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vatTuLayerPaneLayout.createSequentialGroup()
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(vatTuLayerPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17)
                        .addGap(131, 131, 131)
                        .addComponent(jButton18)
                        .addGap(53, 53, 53)))
                .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(vatTuLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        vatTuLayerPaneLayout.setVerticalGroup(
            vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vatTuLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vatTuLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton18)
                    .addComponent(jButton19))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jLabel21.setText("Name");

        jTextField17.setText("jTextField1");

        jLabel22.setText("Date");

        jTextField18.setText("jTextField1");

        jLabel23.setText("Quantity");

        jTextField19.setText("jTextField1");

        jLabel24.setText("Customer");

        jButton24.setText("jButton8");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel25.setText("Statuts");

        jTextField20.setText("jTextField1");

        jButton25.setText("add");

        jButton26.setText("eddit");

        jButton27.setText("remove");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        donViLayerPane.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jTextField17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jTextField18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jTextField19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jButton24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jComboBox5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jTextField20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jButton25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jButton26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jButton27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        donViLayerPane.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout donViLayerPaneLayout = new javax.swing.GroupLayout(donViLayerPane);
        donViLayerPane.setLayout(donViLayerPaneLayout);
        donViLayerPaneLayout.setHorizontalGroup(
            donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donViLayerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donViLayerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(donViLayerPaneLayout.createSequentialGroup()
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(donViLayerPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton25)
                        .addGap(131, 131, 131)
                        .addComponent(jButton26)
                        .addGap(53, 53, 53)))
                .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton27, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(donViLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        donViLayerPaneLayout.setVerticalGroup(
            donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donViLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(donViLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton25)
                    .addComponent(jButton26)
                    .addComponent(jButton27))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jLabel16.setText("Name");

        jTextField13.setText("jTextField1");

        jLabel17.setText("Date");

        jTextField14.setText("jTextField1");

        jLabel18.setText("Quantity");

        jTextField15.setText("jTextField1");

        jLabel19.setText("Customer");

        jButton20.setText("jButton8");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setText("Statuts");

        jTextField16.setText("jTextField1");

        jButton21.setText("add");

        jButton22.setText("eddit");

        jButton23.setText("remove");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        nhaCungCapLayerPane.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jTextField13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jTextField14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jTextField15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jButton20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jComboBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jTextField16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jButton21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jButton22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jButton23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nhaCungCapLayerPane.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout nhaCungCapLayerPaneLayout = new javax.swing.GroupLayout(nhaCungCapLayerPane);
        nhaCungCapLayerPane.setLayout(nhaCungCapLayerPaneLayout);
        nhaCungCapLayerPaneLayout.setHorizontalGroup(
            nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhaCungCapLayerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhaCungCapLayerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nhaCungCapLayerPaneLayout.createSequentialGroup()
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(nhaCungCapLayerPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton21)
                        .addGap(131, 131, 131)
                        .addComponent(jButton22)
                        .addGap(53, 53, 53)))
                .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton23, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(nhaCungCapLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        nhaCungCapLayerPaneLayout.setVerticalGroup(
            nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhaCungCapLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nhaCungCapLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton21)
                    .addComponent(jButton22)
                    .addComponent(jButton23))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jLabel26.setText("Name");

        jTextField21.setText("jTextField1");

        jLabel27.setText("Date");

        jTextField22.setText("jTextField1");

        jLabel28.setText("Quantity");

        jTextField23.setText("jTextField1");

        jLabel29.setText("Customer");

        jButton28.setText("jButton8");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel30.setText("Statuts");

        jTextField24.setText("jTextField1");

        jButton29.setText("add");

        jButton30.setText("eddit");

        jButton31.setText("remove");

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        khachHangLayerPane.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jTextField21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jTextField22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jTextField23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jButton28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jComboBox6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jTextField24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jButton29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jButton30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jButton31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        khachHangLayerPane.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout khachHangLayerPaneLayout = new javax.swing.GroupLayout(khachHangLayerPane);
        khachHangLayerPane.setLayout(khachHangLayerPaneLayout);
        khachHangLayerPaneLayout.setHorizontalGroup(
            khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangLayerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(khachHangLayerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(khachHangLayerPaneLayout.createSequentialGroup()
                                .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(khachHangLayerPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton29)
                        .addGap(131, 131, 131)
                        .addComponent(jButton30)
                        .addGap(53, 53, 53)))
                .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton31, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(khachHangLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        khachHangLayerPaneLayout.setVerticalGroup(
            khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(khachHangLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton29)
                    .addComponent(jButton30)
                    .addComponent(jButton31))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jLabel31.setText("Name");

        jTextField25.setText("jTextField1");

        jLabel32.setText("Date");

        jTextField26.setText("jTextField1");

        jLabel33.setText("Quantity");

        jTextField27.setText("jTextField1");

        jLabel34.setText("Customer");

        jButton32.setText("jButton8");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel35.setText("Statuts");

        jTextField28.setText("jTextField1");

        jButton33.setText("add");

        jButton34.setText("eddit");

        jButton35.setText("remove");

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable7);

        thongKeLayerPane.setLayer(jLabel31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jTextField25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jLabel32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jTextField26, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jLabel33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jTextField27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jLabel34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jButton32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jComboBox7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jLabel35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jTextField28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jButton33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jButton34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jButton35, javax.swing.JLayeredPane.DEFAULT_LAYER);
        thongKeLayerPane.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout thongKeLayerPaneLayout = new javax.swing.GroupLayout(thongKeLayerPane);
        thongKeLayerPane.setLayout(thongKeLayerPaneLayout);
        thongKeLayerPaneLayout.setHorizontalGroup(
            thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLayerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thongKeLayerPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(thongKeLayerPaneLayout.createSequentialGroup()
                                .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(thongKeLayerPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton33)
                        .addGap(131, 131, 131)
                        .addComponent(jButton34)
                        .addGap(53, 53, 53)))
                .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton35, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(thongKeLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        thongKeLayerPaneLayout.setVerticalGroup(
            thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLayerPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(thongKeLayerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton33)
                    .addComponent(jButton34)
                    .addComponent(jButton35))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhapKhoLayerPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nhapKhoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xuatKhoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vatTuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donViButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(khachHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thongKeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(xuatKhoLayerPane)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(vatTuLayerPane)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(donViLayerPane)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(nhaCungCapLayerPane)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(khachHangLayerPane)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(thongKeLayerPane)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vatTuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapKhoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xuatKhoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donViButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khachHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thongKeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhapKhoLayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(xuatKhoLayerPane)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(117, Short.MAX_VALUE)
                    .addComponent(vatTuLayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(117, Short.MAX_VALUE)
                    .addComponent(donViLayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(117, Short.MAX_VALUE)
                    .addComponent(nhaCungCapLayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(117, Short.MAX_VALUE)
                    .addComponent(khachHangLayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(117, Short.MAX_VALUE)
                    .addComponent(thongKeLayerPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhapKhoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhapKhoButtonMouseClicked
        chooseLayer(nhapKhoLayerPane);
    }//GEN-LAST:event_nhapKhoButtonMouseClicked

    private void xuatKhoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xuatKhoButtonMouseClicked
        chooseLayer(xuatKhoLayerPane);
    }//GEN-LAST:event_xuatKhoButtonMouseClicked

    private void vatTuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vatTuButtonMouseClicked
        chooseLayer(vatTuLayerPane);
    }//GEN-LAST:event_vatTuButtonMouseClicked

    private void donViButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donViButtonMouseClicked
        chooseLayer(donViLayerPane);
    }//GEN-LAST:event_donViButtonMouseClicked

    private void nhaCungCapButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhaCungCapButtonMouseClicked
        chooseLayer(nhaCungCapLayerPane);
    }//GEN-LAST:event_nhaCungCapButtonMouseClicked

    private void khachHangButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangButtonMouseClicked
        chooseLayer(khachHangLayerPane);
    }//GEN-LAST:event_khachHangButtonMouseClicked

    private void thongKeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeButtonMouseClicked
        chooseLayer(thongKeLayerPane);
    }//GEN-LAST:event_thongKeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }
    
    /**
     * Chọn LayeredPane để hiển thị
     *
     * @param choose LayeredPane
     */
    public void chooseLayer(JLayeredPane choose) {
        nhapKhoLayerPane.setVisible(false);
        xuatKhoLayerPane.setVisible(false);
        vatTuLayerPane.setVisible(false);
        donViLayerPane.setVisible(false);
        nhaCungCapLayerPane.setVisible(false);
        khachHangLayerPane.setVisible(false);
        thongKeLayerPane.setVisible(false);
        if (choose != null) {
            choose.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donViButton;
    private javax.swing.JLayeredPane donViLayerPane;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton khachHangButton;
    private javax.swing.JLayeredPane khachHangLayerPane;
    private javax.swing.JButton nhaCungCapButton;
    private javax.swing.JLayeredPane nhaCungCapLayerPane;
    private javax.swing.JButton nhapKhoButton;
    private javax.swing.JLayeredPane nhapKhoLayerPane;
    private javax.swing.JButton thongKeButton;
    private javax.swing.JLayeredPane thongKeLayerPane;
    private javax.swing.JButton vatTuButton;
    private javax.swing.JLayeredPane vatTuLayerPane;
    private javax.swing.JButton xuatKhoButton;
    private javax.swing.JLayeredPane xuatKhoLayerPane;
    // End of variables declaration//GEN-END:variables
}
