/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykhohang;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author hungpt
 */
public class ManageStorage extends javax.swing.JFrame {

    /**
     * Creates new form ManageStorage
     */
    public ManageStorage() {
        initComponents();
        this.itemMenu.setVisible(false);
    }
    
    private void changeView(JPanel panel){
        this.itemMenu.setVisible(false);
        this.storageMenu.setVisible(false);
        
        if(panel != null) {
            panel.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemBtn = new javax.swing.JButton();
        importBtn = new javax.swing.JButton();
        exportBtn = new javax.swing.JButton();
        customerBtn = new javax.swing.JButton();
        providerBtn = new javax.swing.JButton();
        statisticBtn = new javax.swing.JButton();
        itemMenu = new javax.swing.JPanel();
        nameInput = new javax.swing.JTextField();
        itemLabel = new javax.swing.JLabel();
        itemCodeInput = new javax.swing.JTextField();
        codeLabel = new javax.swing.JLabel();
        typeItem = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        providerComp = new javax.swing.JComboBox<>();
        providerLabel = new javax.swing.JLabel();
        moneyImportInput = new javax.swing.JTextField();
        moneyImportLabel = new javax.swing.JLabel();
        moneyExportInput = new javax.swing.JTextField();
        moneyExportLabel = new javax.swing.JLabel();
        noteInput = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        addItemBtn = new javax.swing.JButton();
        editItemBtn = new javax.swing.JButton();
        deleteItemBtn = new javax.swing.JButton();
        itemTableContainer = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        storageMenu = new javax.swing.JPanel();
        itemListStorage = new javax.swing.JComboBox<>();
        itemListLabel = new javax.swing.JLabel();
        codeListStorage = new javax.swing.JComboBox<>();
        quantityInputStorage = new javax.swing.JTextField();
        codeListLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        providerList = new javax.swing.JComboBox<>();
        providerStorageLabel = new javax.swing.JLabel();
        storeBtn = new javax.swing.JButton();
        editStorageBtn = new javax.swing.JButton();
        deleteItemStorageBtn = new javax.swing.JButton();
        importContainer = new javax.swing.JScrollPane();
        importTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemBtn.setText("Quản lí vật tư");
        itemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBtnActionPerformed(evt);
            }
        });

        importBtn.setText("Nhập kho");
        importBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importBtnActionPerformed(evt);
            }
        });

        exportBtn.setText("Xuất kho");
        exportBtn.setToolTipText("");

        customerBtn.setText("Khách hàng");

        providerBtn.setText("Nhà cung cấp");

        statisticBtn.setText("Thống kê");

        itemLabel.setText("Tên");

        codeLabel.setText("Mã hàng");

        typeItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        typeLabel.setText("Đơn vị");

        providerComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        providerLabel.setText("Nhà cung cấp");

        moneyImportLabel.setText("Giá nhập");

        moneyExportLabel.setText("Giá xuất");

        noteLabel.setText("Ghi chú");

        addItemBtn.setText("Thêm");

        editItemBtn.setText("Sửa");

        deleteItemBtn.setText("Xoá");

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên", "Mã hàng", "Đơn vị", "Nhà cung cấp", "Số lượng", "Giá nhập", "Giá xuất", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTableContainer.setViewportView(itemTable);
        if (itemTable.getColumnModel().getColumnCount() > 0) {
            itemTable.getColumnModel().getColumn(0).setPreferredWidth(2);
            itemTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            itemTable.getColumnModel().getColumn(3).setPreferredWidth(10);
            itemTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            itemTable.getColumnModel().getColumn(5).setPreferredWidth(5);
            itemTable.getColumnModel().getColumn(6).setPreferredWidth(50);
            itemTable.getColumnModel().getColumn(7).setPreferredWidth(50);
            itemTable.getColumnModel().getColumn(8).setPreferredWidth(150);
        }

        javax.swing.GroupLayout itemMenuLayout = new javax.swing.GroupLayout(itemMenu);
        itemMenu.setLayout(itemMenuLayout);
        itemMenuLayout.setHorizontalGroup(
            itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemMenuLayout.createSequentialGroup()
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(itemLabel)))
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(codeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(itemCodeInput)))
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(typeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(providerComp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(typeLabel)
                                .addGap(73, 73, 73)
                                .addComponent(providerLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addComponent(moneyImportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moneyExportInput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(noteInput)
                                .addContainerGap())
                            .addGroup(itemMenuLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(moneyImportLabel)
                                .addGap(104, 104, 104)
                                .addComponent(moneyExportLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(noteLabel)
                                .addGap(80, 80, 80))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemMenuLayout.createSequentialGroup()
                        .addComponent(addItemBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editItemBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteItemBtn)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemMenuLayout.createSequentialGroup()
                        .addComponent(itemTableContainer)
                        .addContainerGap())))
        );
        itemMenuLayout.setVerticalGroup(
            itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemMenuLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemLabel)
                    .addComponent(codeLabel)
                    .addComponent(typeLabel)
                    .addComponent(providerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyImportLabel)
                    .addComponent(moneyExportLabel)
                    .addComponent(noteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameInput)
                    .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemCodeInput, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(typeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(providerComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moneyImportInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(moneyExportInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(itemMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(editItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        itemListStorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        itemListLabel.setText("Tên sản phẩm");

        codeListStorage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        quantityInputStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityInputStorageActionPerformed(evt);
            }
        });

        codeListLabel.setText("Mã hàng");

        quantityLabel.setText("Số lượng");

        providerList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        providerStorageLabel.setText("Nhà cung cấp");

        storeBtn.setText("Thêm");

        editStorageBtn.setText("Sửa");
        editStorageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editStorageBtnActionPerformed(evt);
            }
        });

        deleteItemStorageBtn.setText("Xoá");

        importTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        importContainer.setViewportView(importTable);

        javax.swing.GroupLayout storageMenuLayout = new javax.swing.GroupLayout(storageMenu);
        storageMenu.setLayout(storageMenuLayout);
        storageMenuLayout.setHorizontalGroup(
            storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storageMenuLayout.createSequentialGroup()
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(storageMenuLayout.createSequentialGroup()
                        .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(itemListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codeListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)
                                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(itemListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(codeListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(quantityInputStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(storageMenuLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(providerStorageLabel))
                            .addGroup(storageMenuLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(providerList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(storageMenuLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(storeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editStorageBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteItemStorageBtn)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addComponent(importContainer)
        );
        storageMenuLayout.setVerticalGroup(
            storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemListLabel)
                        .addComponent(codeListLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityLabel)
                        .addComponent(providerStorageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeListStorage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityInputStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(providerList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(storageMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStorageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteItemStorageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(importContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(providerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statisticBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(storageMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(importBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(providerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statisticBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(itemMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(storageMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importBtnActionPerformed
        changeView(this.storageMenu);
    }//GEN-LAST:event_importBtnActionPerformed

    private void quantityInputStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityInputStorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityInputStorageActionPerformed

    private void editStorageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editStorageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editStorageBtnActionPerformed

    private void itemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBtnActionPerformed
        changeView(this.itemMenu);
    }//GEN-LAST:event_itemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStorage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStorage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel codeListLabel;
    private javax.swing.JComboBox<String> codeListStorage;
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton deleteItemBtn;
    private javax.swing.JButton deleteItemStorageBtn;
    private javax.swing.JButton editItemBtn;
    private javax.swing.JButton editStorageBtn;
    private javax.swing.JButton exportBtn;
    private javax.swing.JButton importBtn;
    private javax.swing.JScrollPane importContainer;
    private javax.swing.JTable importTable;
    private javax.swing.JButton itemBtn;
    private javax.swing.JTextField itemCodeInput;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JLabel itemListLabel;
    private javax.swing.JComboBox<String> itemListStorage;
    private javax.swing.JPanel itemMenu;
    private javax.swing.JTable itemTable;
    private javax.swing.JScrollPane itemTableContainer;
    private javax.swing.JTextField moneyExportInput;
    private javax.swing.JLabel moneyExportLabel;
    private javax.swing.JTextField moneyImportInput;
    private javax.swing.JLabel moneyImportLabel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField noteInput;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JButton providerBtn;
    private javax.swing.JComboBox<String> providerComp;
    private javax.swing.JLabel providerLabel;
    private javax.swing.JComboBox<String> providerList;
    private javax.swing.JLabel providerStorageLabel;
    private javax.swing.JTextField quantityInputStorage;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JButton statisticBtn;
    private javax.swing.JPanel storageMenu;
    private javax.swing.JButton storeBtn;
    private javax.swing.JComboBox<String> typeItem;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
